export const FETCH_DATAJSON_START = 'FETCH_DATAJSON_START';
export const FETCH_DATAJSON_SUCCESS = 'FETCH_DATAJSON_SUCCESS';
export const FETCH_DATAJSON_ERROR = 'FETCH_DATAJSON_ERROR';
export const FETCH_SINGLEJSON_SUCCESS = 'FETCH_SINGLEJSON_SUCCESS';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_OPENCITYMODAL_SUCCESS = 'FETCH_OPENCITYMODAL_SUCCESS';
export const FETCH_MOREPROMO_SUCCESS = 'FETCH_MOREPROMO_SUCCESS';
export const FETCH_LOADCITYLIST_SUCCESS = 'FETCH_LOADCITYLIST_SUCCESS';